export const errorWrongPath = 'Ви обрали дорогу нахуй'
export const errorWrongParameters = 'Неправильні параметри'
export const errorWrongPathname = 'Помилковий pathname'
export const errorNotFound = 'Нічого не знайдено'
export const errorFileNotOpen = 'Файл не відкрито'