export const NAME_CARRIER_INFORMATION = 'CARRIER_INFORMATION.txt'
export const BLOCK_SIZE = 8 //KiB
export const SIZE_CARRIER_INFORMATION = 1024
export const ALL_BLOCKS = SIZE_CARRIER_INFORMATION / BLOCK_SIZE // Integer